### ISSUE TITLE
ClusterTunnel image changes don't propagate to Deployment

### ISSUE THREAD

**Issue by maxpain** [adyanth/cloudflare-operator#113] opened 2024-11-08 18:33 UTC
Hello. I've changed the image of `cloudflared` in `ClusterTunnel` resource, but the `Deployment` didn't upgrade.

**Comment by adyanth** [comment] 2024-11-09 02:43
Duplicate of https://github.com/adyanth/cloudflare-operator/issues/39

**Closed by adyanth** 2024-11-09 02:43 UTC
