### ISSUE TITLE
Allow adjusting tunnel pods resources

### ISSUE THREAD

**Issue by maxpain** [adyanth/cloudflare-operator#112] opened 2024-11-08 18:25 UTC
Hello. It seems currently they are hardcoded
https://github.com/adyanth/cloudflare-operator/blob/main/controllers/reconciler.go#L498

**Comment by adyanth** [comment] 2024-11-09 02:45
Duplicate of https://github.com/adyanth/cloudflare-operator/issues/52#issuecomment-1080879510

**Closed by adyanth** 2024-11-09 02:45 UTC
